### ISSUE TITLE
formatting fails when .php-cs config defines a Finder

### ISSUE THREAD

**Issue by ComaVN** [adael/SublimePhpCsFixer#16]
If I have this in my `.php-cs` config file:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in('src')
    ->in('tests')
;

return PhpCsFixer\Config::create()
    ->setRules([
        '@Symfony' => true,
    ])
    ->setFinder($finder)
;
```
running the formatter fails with `The "src" directory does not exist.`

This is because the file to format is copied to a temp dir, where indeed these directories do not exist.

I don't really see how this can be fixed cleanly, but some ugly solutions come to mind:
 - recreate the (empty) directory structure of the entire project to the temp dir as well. (maybe only to a certain depth. I doubt more than 4 or 5 would ever be needed)
 - parse the `.php-cs` file beforehand, and add only the paths that are explicitly added in the `Finder` to the temp dir
 - parse the `.php-cs` file beforehand, and strip any `Finder`s, and then use that modified config file.

**Comment by ComaVN** [comment]
It could also be argued that this is a bug in php-cs-fixer itself, since it also happens when running `php-cs-fixer fix --path-mode=override path/to/my/file.php`

**Comment by ComaVN** [comment]
Another workaround, that I'm going with for now:
```
+try {
     $finder = PhpCsFixer\Finder::create()
         ->in('src')
         ->in('tests')
     ;
+} catch (\InvalidArgumentException $e) {
+    $finder = [];
+}
```

**Comment by adael** [comment]
Perhaps you should have two separate config files, one for calling php-cs-fixer directly and the another for the plugin. 

Also, I don't know if this fits into your workflow. It have little sense to me to use a finder when you're formatting a view in the editor. I would love to ear any idea about how to use a finder alongside this plugin.

Also we have to consider that you can format some php code in a new view (without an existing file).

Thank you

**Comment by ComaVN** [comment]
Yeah, I'm happy enough with my workaround for now, and I don't think there's really anything this plugin can do about it, so you can close this issue if you want. (although it might be useful to document this behaviour)

**Comment by rginnow** [comment]
My finder isn't failing out as an error, I'm simply unable to tell the fixer to NOT format a file.
I don't want a custom php file that doesn't really need to follow my format rules.

My config:

```php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->notPath('resources/views/pdf/savepdf.php')
;
// I've tried having just the full file path
// the file name itself
// not having the DIR etc.
// Nothing seems to make a difference to the formatter.

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@PSR2' => true, // use normal PSR2 formatting
        'align_multiline_comment' => ['comment_type' => 'phpdocs_only'], // Align the docblock by asterisk
        'array_syntax' => ['syntax' => 'short'], // Force [] syntax
        'binary_operator_spaces' => true,
        'blank_line_after_opening_tag' => true, // for readability, make sure nothing is after the <?php line
        'concat_space' => ['spacing' => 'one'], // force a space when concatinating with a .
        'no_unused_imports' => true, // Make sure the imports are clean and only importing what we use
        'no_empty_comment' => true, // Comments should not be left empty
        'no_empty_phpdoc' => true, // same as above
        'no_useless_else' => true, // if/else statements should be useful, not empty
        'no_whitespace_in_blank_line' => true, // remove extra spaces on empty lines
        'ordered_imports' => ['sortAlgorithm' => 'length'], // order imports by length
        'phpdoc_add_missing_param_annotation' => true, // any missing @params are auto added
        'phpdoc_align' => true, // Align each part of the PHP doc
        'phpdoc_indent' => true, // Indent the docblock to the function
        'phpdoc_order' => true, // Order the annotations by type (@param -> @throw -> @return)
        'phpdoc_separation' => true, // Separate each of the types of annotations
        'psr4' => true, // force filename to match class name
        'single_line_comment_style' => true, // force one-line comments to use the double slash syntax
        'single_quote' => true, // convert "" to '' for simple strings
        'standardize_not_equals' => true, // force != if using <>
    ])->setFinder($finder);

```

**Comment by rginnow** [comment]
So after reviewing my config, it's not wrong. Running the command myself works just fine. I guess i'll have to set the plugin to manual fixing only. I have it running on save.

The only workaround I can see is adding exclude patterns to the plugin itself, and check if the file is in those excludes before creating the temporary file.

**Comment by adael** [comment]
If a finder is configured in the config file, the php-cs-fixer tool will format the included files when called, this is the expected behavior and it doesn't belongs to this plugin to modify it. 

I think it's not a bad idea to have a separate config file without the finder, normally you have to setup its path once in the plugin configuration.

Perhaps there's something i'm missing, and suggestions are welcome.
