### ISSUE TITLE
Exclude some directories

### ISSUE THREAD

**Issue by binalfew** [adael/SublimePhpCsFixer#19]
Is it possible to exclude some directories. I am using a laravel 5.5 project. The fixer flags all files in the tests directory as errors if I am using an underscore in for the method names. 

thanks.

**Comment by orumad** [comment]
++

**Comment by adael** [comment]
I don't understand, what do you mean with "flags all files"?

This plugin simply format an opened file in the editor, so what do you mean?

Thank you.

**Comment by jerrychen1013** [comment]
I also have same issue, some types like vue and js etc., phpcsfixer would also run after save(I set on_save=true).
Has any way to exclude some types' file like vue not to run phpcsfixer? 
Thank you

**Comment by agung-wete** [comment]
there is `exclude `and `notName`
DOC http://symfony.com/doc/current/components/finder.html#file-name
