### ISSUE TITLE
Reference Packages dir

### ISSUE THREAD

**Issue by zoomyboy** [adael/SublimePhpCsFixer#23]
Hello,

I have sublime installed on multiple machines. So it would be nice if I cound reference the config file of phpcsfixer relative to my Packages/User dir. What would be the proper path in such a case?

Also note that the home directory reference "~" doesnt work.

**Comment by adael** [comment]
Sorry for answer some months late, but I didn't knew what to do with your issue until now.

I didn't test this, but perhaps you could use the `packages` variable, something like:

    {config: "${packages}/User/your_cs_config"}

Regards,
