### ISSUE TITLE
Don't run the command if it is not a php file

### ISSUE THREAD

**Issue by predragnikolic** [adael/SublimePhpCsFixer#24]
Helloo :)

I have the run `on_save` setting turned on. And currently if I save the file, reguardless if it is a `.php` file, or `.html` file, `.js` file, the command will run.

But the command should only run if it is a `.php` file.

I can make a PR if you like?

**Comment by adael** [comment]
Sure!, I'll review your PR asap. Please note that there are more extensions
that needs support, like *.ctp for cakephp views, and I'm sure there's
several more.

Perhaps we can check if the SublimeView syntax it's php before calling the
formatter.

Regards,

**Comment by predragnikolic** [comment]
I made a PR, please say if you have any questions, suggestions.
