### ISSUE TITLE
Certain config options not working

### ISSUE THREAD

**Issue by minikN** [adael/SublimePhpCsFixer#26]
Hello, I'm trying to use the plugin, I created my config like so

    <?php

    $finder = PhpCsFixer\Finder::create()
        ->in(__DIR__)
    ;

    return PhpCsFixer\Config::create()
        ->setRules([
            '@PSR2' => true,
            '@Symfony' => true,
            'array_syntax' => ['syntax' => 'short'],
            'no_unused_imports' => true,
            'binary_operator_spaces' => ['default' => 'align'],
        ])
        ->setFinder($finder);

The config is working, however `'binary_operator_spaces' => ['default' => 'align']` doesn't. So for example

    return Validator::make($data, [
                    'name' =>    'required|string|max:255',
                'email' =>   'required|string|email|max:255|unique:users',
                'password' => 'required|string|min:6|confirmed',
            ]);

doesn't change upon saving. What am I doing wrong?

**Comment by adael** [comment]
This plugin only tells to phpcsfixer what file to format and what config to use. If some options are not working while others do perhaps it's a bug in the phpcsfixer (which  I sincerely doubt because it's a great utility) or a misconfiguration.

Also I couldn't figure out how to use the finder feature with this plugin, because the way it works is formatting a view, not several files located by a finder as in your config.

**Comment by minikN** [comment]
Okay, I figured it out. 

Apparently one can't use `~` in the config file. I was specifying my config file like so in the user settings:

`"config": "~/Library/Mobile Documents/com~apple~CloudDocs/Settings/.phpcsfixer"`

the console wasn't outputting any error messages. However I found out it wasn't using the config file. I changed it to

``"config": "/Users/Artemios/Library/Mobile Documents/com~apple~CloudDocs/Settings/.phpcsfixer"``

and what do you know, it's working now. I guess this is my fault, since the docs specify to add a path like this: `"config": "/path/to/.phpcsfixer"`. However for some reason I just assumed you can use the shorthand. My bad.

Maybe this helps some people. Can be closed. Thanks!
