### ISSUE TITLE
Usage with .phar

### ISSUE THREAD

**Issue by higoka** [adael/SublimePhpCsFixer#27]
Allow usage without composer instead use the php-cs-fixer.phar executable.

**Comment by adael** [comment]
Didn't tested directly but my guess it's that if you make it executable and configure the path settings in sublime as follows, it should work:

```
// SublimePhpCsFixer Settings
{
  path": "/path/to/php-cs-fixer.phar"
}
```

Another alternative is create a symlink to the phar file:

`ln -s /path/to/php-cs-fixer.phar $HOME/bin/php-cs-fixer`

**Comment by higoka** [comment]
Ok got it working. I only have one more problem. The exclude in my .phpcs file doesnt work. I think its because the --path-mode should be intersection. But there is no option to set it.
