### ISSUE TITLE
How to auto format on save?

### ISSUE THREAD

**Issue by Fossil01** [adael/SublimePhpCsFixer#29]
How do I enable php-cs-fixer to run when saving a .php file in ST3?

**Comment by felixpenrose** [comment]
Can you explain why you closed this? Did you find out how to do it? If so please can you share your solution. Or if it's not possible, please say so.

**Comment by Fossil01** [comment]
Switched to VS Code.

**Comment by felixpenrose** [comment]
Right OK, thanks.
