### ISSUE TITLE
Variables not loaded

### ISSUE THREAD

**Issue by sander3** [adael/SublimePhpCsFixer#38]
Hi there,

SublimePhpCsFixer stopped working for me yesterday since merging https://github.com/adael/SublimePhpCsFixer/pull/36/files#diff-1dd779ae4db47cc8b575f24096954620e8138e37fdcf66f7085abaf15f315281R278-R280

I believe `plugin_loaded()` fires too soon which makes it impossible to replace the `${folder}` variable in the package config when using Sublime Text projects. Manually disabling and re-enabling the package resolves the issue.

Could you please revert the changes made to loading the variables during formatting files?

**Comment by adael** [comment]
Yes, let me look at it. Thanks you!

**Comment by adael** [comment]
I think it's done. Tell me if works for you! 
Thanks again

**Comment by sander3** [comment]
Works for me! Thank you very much 👍
