### ISSUE TITLE
How to run it on file save?

### ISSUE THREAD

**Issue by zigi05** [adael/SublimePhpCsFixer#43]
How do I make it run on file save?

**Comment by adael** [comment]
You could add this to your Keybinding Settings. In example I use F11 key to format:

```
{
    "keys": ["f11"],
    "command": "sublime_php_cs_fix",
    "context": [
        {
            "key": "selector",
            "operator": "equal",
            "operand": "source.php"
        }
    ]
}
```

**Comment by zigi05** [comment]
Actually I just added this setting that I found in this repo, and it did it: `"on_save": true,`
