### ISSUE TITLE
UTF-8 formatting error e.g. German umlauts

### ISSUE THREAD

**Issue by sjess** [adael/SublimePhpCsFixer#5]
Hi,

I found a little problem in the script, because everytime I used the plugin it changed my "ä" into "Ã¤". 

So I fixed it myself by adding in line 75 the encoding part:

`with open(tmp_file, 'r', encoding='utf8') as file:`

cheers

**Comment by hakanersu** [comment]
Yep fixed my issue too. You can send a pull request.

**Comment by hakanersu** [comment]
and if you gettin UnicodeDecodeError: 'ascii' codec can't decode byte like;

```python
import sys
if sys.version[0] == '2':
    reload(sys)
    sys.setdefaultencoding("utf-8")
```

**Comment by adael** [comment]
Thank you very much
